### ISSUE TITLE
Does not fully work on 32-bit devices like Raspberry Pi

### ISSUE THREAD

**Issue by EdJoPaTo** [ayrat555/frankenstein#10]
`isize` uses the host bits and this might be not enough in some cases. The supergroup chatid is too large for `i32` for example.

Running `cargo check --all-targets` on a 32-bit Raspberry Pi prints out a lot of these errors:
```
error: literal out of range for `isize`
    --> src/api_impl.rs:1450:59
     |
1450 |         params.set_chat_id(Some(ChatIdEnum::IsizeVariant(-1001368460856)));
     |                                                           ^^^^^^^^^^^^^
     |
     = note: the literal `1001368460856` does not fit into the type `isize` whose range is `-2147483648..=2147483647`
```

Personal opinion: `isize` shouldn't be used anywhere but I think a lot of these types are auto generated?

I would change chat id to `i64`, user id to `u64` (they are never negative) and the dates to `u64` (unix timestamps). `ChatIdEnum::IsizeVariant` should also be renamed to not include the "size" in its name. Maybe `ChatIdEnum::IntegerVariant`. This will be a breaking change.

The rest should also be changed (`max_connections` for example is always positive → `usize` or `u32`) but will probably just work as the [telegram api states everything fits into 32-bit signed? integer](https://core.telegram.org/bots/api#available-types).

I don't know if i should just provide a PR or if there is some auto generation logic involved here which has to be adapted.

**Comment by ayrat555** [comment]
@EdJoPaTo thank you for this issue. 
It would be great if you created a PR.

 Initial structs were generated by a generator. But I had to make some manual changes to them

**Comment by ayrat555** [comment]
@EdJoPaTo will you work on this or should I make the requested changes myself?

**Comment by ayrat555** [comment]
@EdJoPaTo thank you for your contribution!

**Comment by EdJoPaTo** [comment]
Just wanted to continue on it and saw, there is already more done, awesome!

Another thought I had: officially 32bit signed integer are supported for the numbers. so most types should be i32. For some like width this does not make sense like amount. amount is always positive so u32 seems the right way. But bigger u32 numbers will end up being negative i32 numbers when passed. Maybe u16 is a better way to go to make sure they will be both positive and fit inside i32.

**Comment by EdJoPaTo** [comment]
Interesting find: https://core.telegram.org/bots/api#chatinvitelink states 1-99999 which is bigger than 2^16. When placed inside an i32 (what they suggest) the number will flip and ends up being negative… no clue how they handle something like that.

**Comment by EdJoPaTo** [comment]
Also: current supergroup member limit is 100k? higher? also above 2^16 but https://core.telegram.org/bots/api#getchatmemberscount also just states Int. Keeping `u32` and not reducing towards `u16` is probably a good idea.
