### ISSUE TITLE
Telegram client implementation

### ISSUE THREAD

**Issue by cavazzatommaso** [ayrat555/frankenstein#140]
I wanted to know if it was possible to authenticate to Telegram as a client using this library. 

I was looking for something similar to Gram Js and came across this library, but it seems that authentication through API_ID, HASH, and SESSION is not possible.

**Comment by EdJoPaTo** [comment]
This is a bot API client library, not a user-bot client library.

You might have luck with [running your own bot api server which offers a user mode](https://github.com/tdlight-team/tdlight-telegram-bot-api#user-mode).
