### ISSUE TITLE
MaybeInaccessibleMessage always becomes Message during deserialization

### ISSUE THREAD

**Issue by trrk** [ayrat555/frankenstein#141]
Within the MaybeInaccessibleMessage, there exist variants Message and InaccessibleMessage. During deserialization, it seems that it always becomes a Message.

Upon reviewing the documentation of the Telegram API, it appears that the determination between InaccessibleMessage and Message can be made based on whether the value of the 'date' is 0 or not.

**Comment by trrk** [comment]
Upon considering the practical use of the code, it was realized that handling scenarios where deserialization may vary could be cumbersome. In my specific case, the following code was necessary.  Therefore, in the end, specifying deserialization to Message at all times might be a more convenient specification. 
```rust
let message_id = cq.message.map(|message| {
    match message {
        MaybeInaccessibleMessage::Message(m) => MessageIdentifier {
            chat_id: m.chat.id,
            message_id: m.message_id,
        },
        MaybeInaccessibleMessage::InaccessibleMessage(m) => MessageIdentifier {
            chat_id: m.chat.id,
            message_id: m.message_id,
        },
    }
});
```

**Comment by EdJoPaTo** [comment]
I wouldn't like putting them together especially as the API actively separates them. The serialization should be fixed, so it's correctly handled on the Rust side of things.
