### ISSUE TITLE
Question regarding UpdateContent

### ISSUE THREAD

**Issue by ale-ben** [ayrat555/frankenstein#168]
I'm trying to allow only specific users to access the bot.
This is done by having an authenticate function called in getUpdates, the function checks the sender id against a list of known ids.

Authenticate is implemented as follows:
```rust
pub fn authenticate(msg: &Message) -> bool {
    if let Some(user) = &msg.from {
        AUTHORIZED_USERS.into_iter().any(|usr| usr.1 == user.id)
    } else {
        false
    }
}
```

This worked fine as long as I only handled incoming updates with type `Message`.
To expand this to other `UpdateContents`, I am considering using a trait as parameter type (`pub fn authenticate(msg: &impl TRAIT_NAME)` but I haven't been able to find a trait describing the incoming update.

Am I missing something or it hasn't been implemented?

**Comment by ayrat555** [comment]
hey. you should specify the types of updates you want to receive as a parameter to `getUpdates`

https://core.telegram.org/bots/api#getupdates

```
Specify an empty list to receive all update types except chat_member, message_reaction, and message_reaction_count (default). If not specified, the previous setting will be used.
```

**Comment by ale-ben** [comment]
Sorry, I probably expressed myself poorly…
I already filtered the updates. 
Question was if here is a way to abstract the common traits of the possible updates, to extract the sender id without getting to the specific types (Message, CallbackQuery, ...)

**Comment by ayrat555** [comment]
thanks for explaining. unfortunately it's not possible
