### ISSUE TITLE
--no-default-features doesnt compile

### ISSUE THREAD

**Issue by EdJoPaTo** [ayrat555/frankenstein#29]
The feature `impl` exists but I'm not sure why or what the benefits are.
Compiling without the feature isnt possible either.

What's the idea behind `impl` where does it help me?

**Comment by ayrat555** [comment]
Hello, @EdJoPaTo 

Ureq api implementationis is in `impl` feature so users can replace default HTTP clients in their projects.

for example, in https://github.com/ayrat555/el_monitorro `isahc` is used instead of `ureq` https://github.com/ayrat555/el_monitorro/blob/master/Cargo.toml#L17
