### ISSUE TITLE
Migrate to builder with compile time checks

### ISSUE THREAD

**Issue by EdJoPaTo** [ayrat555/frankenstein#46]
The used [`derive_builder`](https://crates.io/crates/derive_builder) crate does the checks on runtime. Something like the following will compile but fail at runtime creating hard to find mistakes. Especially as Telegram interactions are not always tested this easily allows for mistakes.

```rust
SendMessageParamsBuilder::default().build().expect("I will fail");
```

```plaintext
I will fail: UninitializedField("chat_id")
```

[`typed-builder`](https://crates.io/crates/typed-builder) does this at compile time which will result in less `.unwrap()`, better performance and less mistakes in production as mistakes are found at compile time. I haven't tried migrating to typed-builder so there might be something preventing it to be used.

Switching the builder system will result in a breaking change but this seems worth it for me.

Any thought on that?

**Comment by ayrat555** [comment]
@EdJoPaTo I don't have anything against this. I think we can try this crate
