### ISSUE TITLE
Keyboard buttons example?

### ISSUE THREAD

**Issue by krims0n32** [ayrat555/frankenstein#55]
Hello, thank you for your crate!

Edit: i've found a bot commands example in the tests in your code.

I was wondering if you could add an example that uses (inline) buttons in the chat? I can't figure it out.

https://core.telegram.org/api/bots/buttons

**Comment by ayrat555** [comment]
@krims0n32 Hello. I added examples in this pr - https://github.com/ayrat555/frankenstein/pull/56
