### ISSUE TITLE
Handling connection issues

### ISSUE THREAD

**Issue by krims0n32** [ayrat555/frankenstein#74]
Hi, thanks for your crate, it works very well. 

 have one issue with it, it seems the get_updates call gets stuck and never returns (not even an Err) when there is a connection issue. I simulate this connection issue by toggling my wifi off on my dev environment, to make my app resilient to this type of problem. I'm using AsyncApi, and the latest frankenstein version.

Do I need to pass additonal parameters to the GetUpdateParams builder? I currently pass .timeout(10_u32) and .allowed_updates() with the Message and CallbackQuery enums.

Thanks!

**Comment by pxp9** [comment]
Did you put .await ? For me works perfectly. 

See my example :D
 
https://github.com/pxp9/weather_bot_rust/blob/master/src/main.rs

**Comment by ayrat555** [comment]
@krims0n32 I could reproduce your problem. I was able to resolve it by adding a timeout to requests.

I'll try to implement it as a fix soon.

@pxp9 thank you for your engagement

**Comment by ayrat555** [comment]
@krims0n32 hello.

can you please try https://github.com/ayrat555/frankenstein/pull/77?

**Comment by krims0n32** [comment]
Hello, seems to be working now! Thanks for the quick fix.
