### ISSUE TITLE
How can you filter on incoming updates?

### ISSUE THREAD

**Issue by PXNX** [ayrat555/frankenstein#75]
Not an issue, but I couldn't find a place to ask.

**Comment by pxp9** [comment]
You do not filter updates, you should do a state program and somehow remember the state of every user that uses the bot , maybe you can do a HashMap or a DB like Postgres. 

You can see my bot as an example of how to make an state machine, in my bot i keep the state of every user in my db with another information.

https://github.com/pxp9/weather_bot_rust/blob/master/src/main.rs

Good luck @PXNX !

**Comment by ayrat555** [comment]
@pxp9 thank you 

@PXNX if you have additional questions, don't be afraid to ask

**Comment by ayrat555** [comment]
can you elaborate on what you mean by filtering?

- to filter by the command, you should match it
https://github.com/ayrat555/el_monitorro/blob/master/src/bot/handler.rs#L85

- to filter by the message type, you should pass AllowedUpdate type

https://github.com/ayrat555/frankenstein/blob/master/src/api_params.rs#L248
