### ISSUE TITLE
Would like to put my example bot in README  ?

### ISSUE THREAD

**Issue by pxp9** [ayrat555/frankenstein#79]
Hi @ayrat555 , Awesome library.

I was wondering if you would like us to put my bot in the README.
My bot is done with this library and i think is a good example to beginners.

https://github.com/pxp9/weather_bot_rust

Maybe you can put it in this README section.
![image](https://user-images.githubusercontent.com/48651252/179195472-7e0a0316-4926-4bbf-a7f8-41fbb63cedb4.png)

Thank you for this awesome tool for building creative and wonderful bots.

**Comment by ayrat555** [comment]
@pxp9 of course.

You can create a pr with the following changes

```
You can check out real-world bots created using this library:

-  https://github.com/helikon-labs/subvt-backend/tree/main/subvt-telegram-bot - A telegram bot for the validators of the [Polkadot](https://polkadot.network/) and [Kusama](https://kusama.network/).
 - https://github.com/ayrat555/el_monitorro - RSS/Atom/JSON feed readeer
 - https://github.com/EdJoPaTo/wdr-maus-downloader - checks for a new episode of the WDR Maus and downloads it
 - https://github.com/pxp9/weather_bot_rust - weather bot

```

**Comment by EdJoPaTo** [comment]
Please do not add my wdr-maus-downloader as its definitely not something a beginner would like to use. It does status updates via Telegram and is not interactive. Yeah it could be hinted towards someone that is interested but its not a good example :innocent:

**Comment by pxp9** [comment]
@EdJoPaTo i have already add it because the comment does not mention beginners bots , it mentions real-world bots
