### ISSUE TITLE
codegen to maintain API

### ISSUE THREAD

**Issue by 7flash** [ayrat555/frankenstein#87]
Perhaps struct definitions should be auto generated to keep in sync with current API?

Noticed another library approach doing that.. 

https://github.com/ferrisgram/ferrisgram

**Comment by ayrat555** [comment]
Hello. I'm sorry for the late reply. just saw this issue

I think it would be nice to have

for the first version of the library I've been using a custom generator - https://github.com/ayrat555/frankenstein_creator

If anyone is willing to resurrect this project or create a new one I'd be happy 

@7flash what do you think?

**Comment by ayrat555** [comment]
closing since not activity here ;[
